### ISSUE TITLE
Issues with podspec

### ISSUE THREAD

**Issue by sethdeckard** [bidmachine/BidMachine-Google-Mobile-Ads-iOS-Adapters#8]
Hi,
There are a couple issues with the latest podspec: https://github.com/CocoaPods/Specs/blob/master/Specs/9/f/e/GoogleMobileAds-BidMachine-Adapters/1.9.2.0/GoogleMobileAds-BidMachine-Adapters.podspec.json

1. Lack of `arm64` support for simulator SDK:
```ruby
  "pod_target_xcconfig": {
    "VALID_ARCHS": "arm64 armv7 armv7s x86_64",
    "VALID_ARCHS[sdk=iphoneos*]": "arm64 armv7 armv7s",
    "VALID_ARCHS[sdk=iphonesimulator*]": "x86_64"
  },
```

Fix: `"VALID_ARCHS[sdk=iphonesimulator*]": "x86_64 arm64"` (assumes that all this pod's dependencies that use frameworks support arm64 in their iOS simulator SDK framework)

2. `user_target_xcconfig` should probably be removed:
```ruby
  "user_target_xcconfig": {
    "VALID_ARCHS": "arm64 armv7 armv7s x86_64",
    "VALID_ARCHS[sdk=iphoneos*]": "arm64 armv7 armv7s",
    "VALID_ARCHS[sdk=iphonesimulator*]": "x86_64"
  },
```

https://guides.cocoapods.org/syntax/podspec.html#user_target_xcconfig

> This attribute is not recommended as Pods should not pollute the build settings of the user project and this can cause conflicts.

**Comment by AssasinSC** [comment]
@sethdeckard Hi. We update the adapter with the latest version of sdk BM & Admob. And add support for arm64 for simulator

**Comment by sethdeckard** [comment]
Thank you @AssasinSC, much appreciated.

**Comment by AssasinSC** [comment]
https://github.com/CocoaPods/Specs/blob/master/Specs/9/f/e/GoogleMobileAds-BidMachine-Adapters/1.9.4.0/GoogleMobileAds-BidMachine-Adapters.podspec.json

@sethdeckard ^

**Comment by sethdeckard** [comment]
Thank you for being so responsive and taking care of this. I really appreciate it. Cheers!
