### ISSUE TITLE
Support Google-Mobile-Ads-SDK 9.8.x

### ISSUE THREAD

**Issue by sethdeckard** [bidmachine/BidMachine-Google-Mobile-Ads-iOS-Adapters#9]
Could we please get a bump to the pod that supports Google-Mobile-Ads-SDK 9.8.x?

https://github.com/CocoaPods/Specs/blob/master/Specs/9/f/e/GoogleMobileAds-BidMachine-Adapters/1.9.2.0/GoogleMobileAds-BidMachine-Adapters.podspec.json

Latest podspec supports 9.3.x:
```ruby
"Google-Mobile-Ads-SDK": [
      "~> 9.3.0"
    ]
```

Thank you

**Comment by AssasinSC** [comment]
https://github.com/bidmachine/BidMachine-Google-Mobile-Ads-iOS-Adapters/releases/tag/v1.9.4.0

@sethdeckard ^
